In [3]:
import numpy as np

myarray = np.array([[15, 5, 1], [29, 12, 3], [43,33,5], [25,27,4]])

print(myarray)

print(myarray.mean())

print(myarray.max())

[[15  5  1]
 [29 12  3]
 [43 33  5]
 [25 27  4]]
16.833333333333332
43


In [7]:
import pandas as pd
ligne_noms = ['ali', 'badr', 'cimon','rachid']
colonne_noms = ['age', 'score', 'bonus']
data_df = pd.DataFrame(myarray, index=ligne_noms, columns=colonne_noms)

In [8]:
print(data_df['age'])

print(data_df.mean())

print(data_df.max())

print(data_df.loc[:,'age'])

print(data_df.iloc[:,[1,2]])

ali       15
badr      29
cimon     43
rachid    25
Name: age, dtype: int64
age      28.00
score    19.25
bonus     3.25
dtype: float64
age      43
score    33
bonus     5
dtype: int64
ali       15
badr      29
cimon     43
rachid    25
Name: age, dtype: int64
        score  bonus
ali         5      1
badr       12      3
cimon      33      5
rachid     27      4


In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
nom_du_fichier_csv = "Social_Network_Ads.csv"
chemin_complet = "C:\\Users\\hil\\Documents\\ilyas\\5IIR14\\system info geo\\TP1\\" + nom_du_fichier_csv
dataset = pd.read_csv(chemin_complet)
print(dataset.head())

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0


In [12]:
from sklearn.preprocessing import LabelEncoder
dataset['Gender']= LabelEncoder().fit_transform(dataset['Gender'].astype(str))
X = dataset.iloc[:, [1, 3]].values
Y = dataset.iloc[:, 4].values

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [23]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)

X_test = sc.transform(X_test)

In [24]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [26]:
y_pred = classifier.predict(X_test)
print(y_pred)

[1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 1 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0
 0 1 1 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 1 1 0 1
 0 0 0 0 1 1 1 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1 0 1 0 1]


In [29]:
c=0
for i in range(0,len(y_pred)):
    if(y_pred[i]==y_test[i]):
        c=c+1
        accuracy=c/len(y_pred)
print("Accuracy is")
print(accuracy)

Accuracy is
0.74


In [30]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
matrice_conf=pd.DataFrame(cm,index=['positive','négative'],columns=['positive','negative'])

In [31]:
X = dataset.iloc[:, [1,2,3]].values
Y = dataset.iloc[:, 4].values

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [33]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)

X_test = sc.transform(X_test)

In [34]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [35]:
y_pred = classifier.predict(X_test)
print(y_pred)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 1 1 1]


In [36]:
c=0
for i in range(0,len(y_pred)):
    if(y_pred[i]==y_test[i]):
        c=c+1
        accuracy=c/len(y_pred)
print("Accuracy is")
print(accuracy)

Accuracy is
0.93


In [38]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
matrice_conf=pd.DataFrame(cm,index=['positive','négative'],columns=['positive','negative'])
print(matrice_conf)

          positive  negative
positive        64         4
négative         3        29
